### ISSUE TITLE
Translator class Constructor they had changed the Argument "sample_rate" to "dtype"

### ISSUE THREAD

**Issue by Nithin412** [camenduru/seamless-m4t-colab#2]
Translator class Constructor they had changed the Argument "sample_rate" to "dtype". Due to this and someother changes entire flow is broke. If you do this changes and push, it will help other people as well.

**Comment by rsreetech** [comment]
Even i had to make this change for this collab to work

**Comment by camenduru** [comment]
thanks for the info ❤ please try again

**Comment by Nithin412** [comment]
thanks camenduru
